### ISSUE TITLE
KeyError while creating ietrans predictions

### ISSUE THREAD

**Issue by Florian-Barthel** [franciszzj/HiLo#5]
Hello,
I'm currently trying to reproduce your results following your training instructions. However, when creating the predictions for ietrans using tools/data_prepare/ietrans.py I'm getting a KeyError when accessing data['gt_labels'] in line 59. 

```python
with torch.no_grad():
    device = data['gt_labels'][0].data[0][0].device # KeyError: 'gt_labels'
```

I have changed the test split in openpsg/datasets/psg.py (Line 162) as suggested in ietrans.py:
```python
elif split == 'test':
    # self.data = [
    #     d for d in dataset['data']
    #     if d['image_id'] in dataset['test_image_ids']
    # ]
    # If you need to traverse all data
    self.data = [
         d for d in dataset['data']
    ]
```

Do I have to make any further changes to either openpsg/datasets/psg.py or tools/data_prepare/ietrans.py?

Currently, the data object in ietrans.py only consists of {"img_meta": ..., "img": ...}, while gt_labels, gt_masks, gt_bboxes and gt_rels are missing.

**Comment by franciszzj** [comment]
You don't need to make further modifications to the ietrans.py. I ran it locally again and found no issues. Can you add a breakpoint with `pdb` at the point where you get an error for debugging?

Additionally, I have already open-sourced the processed data in the README. You can directly use the processed data for model training.

I've closed this issue. If you have further questions, feel free to reopen it or submit a new issue.

**Comment by Florian-Barthel** [comment]
Thank you for your response and for uploading the processed data! That helps a lot!

ietrans.py is running for me as well, when making no modifications. However, by default only test images are iterated which are being skipped in line 56.

As soon as I change the psg.py (as stated above) to iterate all data, not only the test data, i run into the aforementioned KeyError. This also makes sense for me, as my data item only has "img_metas" and "img" when inspecting it with the debugger:

```
data = {dict: 2} {
   'img_metas' = {list: 1} [DataContainer([...])]
   'img' = {list: 1} [tensor(...)]
```

I think this is because in the config the test_pipeline is configured to collect only the key "img". ( dict(type='Collect', keys=['img'])). However, when I extend this, I get another error.

**Comment by Florian-Barthel** [comment]
Thanks so much! This solved my issue.
